# Generated by Django 3.2.7 on 2021-09-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='año',
        ),
        migrations.AlterField(
            model_name='curso',
            name='año_cursada',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preno.categoria'),
        ),
    ]
